### ISSUE TITLE
3.0 Expanded scope to include coded contraindications and series based on patient risk

### ISSUE THREAD

**Issue by Hjhawley** [immregistries/StepIntoCDSI#5]
Additional data structure we have to add? scope of what? Where does this fit?

**Comment by nathanbunker** [comment]
This is an interesting question. The original CDSi project focused on "aged-based' recommendations which are recommendations that can be made knowing only the patient's age and vaccination history. This is the "health" child and adult schedules, without all the exceptions for different circumstances. The top priority for this is to get the "aged-based" recommendations working again, but if we can also support contraindications and patient risk, that would be great. 

I have another project, which I'm trying to get funding for that will create a new standard for how forecasting will work beyond aged-based and if CDSi supports this it could be used to demonstrate this new standard. This will will open up new avenues for demonstrating our student project.
